// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1a1WaBBLsZMZW6xDdAUzc3_RoXLE7e3M',
    appId: '1:608870837825:android:e2aabab507d9bf2c7b20c0',
    messagingSenderId: '608870837825',
    projectId: 'carkigo',
    storageBucket: 'carkigo.firebasestorage.app',
  );

  /// Google Sign-In için Web Client ID (zorunlu).
  /// 1. Firebase Console: https://console.firebase.google.com/
  /// 2. Projenizi seçin → Authentication → Sign-in method → Google'ı etkinleştirin
  /// 3. "Web client ID" ve "Web client secret" alanlarını kopyalayın
  /// 4. Buraya Web client ID'yi yapıştırın (örn: 123456789-xxx.apps.googleusercontent.com)
  /// 5. android/app/google-services.json dosyasını yeniden indirin (SHA-1 eklediyseniz)
  static const String? googleWebClientId = '608870837825-8lr5b0mg42qrhtletgbnuv9kb4qpicqq.apps.googleusercontent.com';

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArToPGBztKpDnKfhR7jMBTp7duTfwQbMo',
    appId: '1:608870837825:ios:d63f3fc919fd2a9a7b20c0',
    messagingSenderId: '608870837825',
    projectId: 'carkigo',
    storageBucket: 'carkigo.firebasestorage.app',
    iosBundleId: 'com.sanscarki.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR181Oyxi_g_rrJvOO8rwpJWk2evnADQU',
    appId: '1:608870837825:web:4fe1bc99121c28f77b20c0',
    messagingSenderId: '608870837825',
    projectId: 'carkigo',
    authDomain: 'carkigo.firebaseapp.com',
    storageBucket: 'carkigo.firebasestorage.app',
    measurementId: 'G-J0N3GN0T7X',
  );

}